### ISSUE TITLE
Entity not found

### ISSUE THREAD

**Issue by IlexPauc** [manhtai/vitalsource-printer#1]
I was able to get the screen coordinates and install the dependencies but actually running the program returns this traceback:

Take book screenshot at (777, 80) (1479, 985) and next at (1888, 535) with 1623 pages
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    images = screenshot(top_left, right_bottom, next_button, total_page)
  File "app.py", line 17, in screenshot
    autopy.bitmap.capture_screen((top_left, rect_size)).save(file_name)
FileNotFoundError: [Errno 3] entity not found

When I run the program from Windows powershell, it will click the next page button in Bookshelf then stop.

**Comment by manhtai** [comment]
I've pushed a fix for this problem, please pull the code and try again.

**Comment by IlexPauc** [comment]
Works perfectly now. Thanks for the assist.
