### ISSUE TITLE
.vbk to pdf in windows

### ISSUE THREAD

**Issue by HARSHATEJA1998** [manhtai/vitalsource-printer#6]
Hi manhtai,

Could you please assist in resolving this error?

usage: app.py [-h] top_left right_bottom next_button total_page
app.py: error: the following arguments are required: top_left, right_bottom, next_button, total_page

I understand that it needs the coordinates of top_left position and right_bottom position and position of next button.
But what is total_page attribute?

How can I get these position values?

Thanks & Regards,
Harsha Teja G

**Comment by manhtai** [comment]
total_page is the total page of your vitalsource book.

**Comment by HARSHATEJA1998** [comment]
So the other coordinates . how can I pinpoint them?

**Comment by manhtai** [comment]
I don't know, but you can try googling for `get mouse coordinates in windows`. Good luck.

**Comment by HARSHATEJA1998** [comment]
Appreciate the efforts on the code.
Thanks for quick assistance.

Have a great day
